Global:
  infer_imgs: ""
  inference_model_dir: "./models/image_orientation_infer"
  batch_size: 1
  use_gpu: False
  enable_mkldnn: False
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ToCHWImage:

PostProcess:
  main_indicator: Topk
  Topk:
    topk: 1
    class_id_map_file: "../ppcls/utils/PULC_label_list/text_image_orientation_label_list.txt"